### ISSUE TITLE
不能正确加载库

### ISSUE THREAD

**Issue by Tritoce** [NekoRabi/Majsoul-QQBot#1]
启动main.py产生
root@Tritoce:/var/soft/Majsoul-QQBot-0.5.5# python3 main.py 
Traceback (most recent call last):
  File "/var/soft/Majsoul-QQBot-0.5.5/main.py", line 7, in <module>
    from plugin import *
  File "/var/soft/Majsoul-QQBot-0.5.5/plugin/__init__.py", line 9, in <module>
    from plugin.TenHouPlugin import *
  File "/var/soft/Majsoul-QQBot-0.5.5/plugin/TenHouPlugin/__init__.py", line 4, in <module>
    from plugin.TenHouPlugin.TenHou import asyautoget_th_matching, addthwatch, asyautoget_th_match, removethwatch, \
ImportError: cannot import name 'autoget_th_matching' from 'plugin.TenHouPlugin.TenHou' (/var/soft/Majsoul-QQBot-0.5.5/plugin/TenHouPlugin/TenHou.py)
而后崩溃无法使用

**Comment by NekoRabi** [comment]
很抱歉未提交init.py的修改，release中是正常使用的版本，我将检测github的代码，和我本地做对比

**Comment by NekoRabi** [comment]
代码已更新，包应该会正确引用了，错误的引用删完了

**Comment by Tritoce** [comment]
之前的错误是在使用release的源代码产生的
刚才试了下新的产生：
root@Tritoce:/var/soft/Majousl# python3 main.py 
'gbk' codec can't decode byte 0x97 in position 114: illegal multibyte sequence 缺失
文件打开错误，尝试生成初始文件中...
默认文件生成完成，请重新启动。
