### ISSUE TITLE
雀魂十连的角色图像显示问题

### ISSUE THREAD

**Issue by LozenChen** [NekoRabi/Majsoul-QQBot#3]
![QQ图片20220801201754](https://user-images.githubusercontent.com/68326284/182265923-8ad2a260-dcae-447d-a944-c15056c021c9.png)
如图 , 我们见到角色和黑底之间有一圈灰色的边 , 细看来十分不美观
这应该是因为作者使用的源素材是角色周围带透明的 png 文件 , 然后没怎么处理就直接输出了 ?
解决方案是 , 先用任何能处理透明度的软件/手动代码实现 , 将源素材叠在黑底上 (雀魂官方的抽卡是深紫色的底...效果差不多), 然后再一起裁剪成 180*180 像素的图片输出

**Comment by NekoRabi** [comment]
谢谢的你的反馈，已经修复了角色黑边的问题。
解决方法是 img.paste() 加入mask参数来保存原图片的alpha通道信息
