### ISSUE TITLE
天凤插件pt计算有误

### ISSUE THREAD

**Issue by Sunshine40** [NekoRabi/Majsoul-QQBot#5]
对于老号而言，新人~4级的升段pt是30, 30, 30, 60, 60, 60, 90，与现行不同，因此对这些账号计算pt会有错误。

我可以自己改代码，如果需要，也可以fork之后提交pull request。但我就很奇怪，现在存活于很多群里的机器人查到的pt是没有错误的，这些机器人到底是谁维护的，看上去好像就是同款机器人，但是代码版本要新很多，还有包括ob对局播报小局和牌等不存在于github代码库中的功能

**Comment by NekoRabi** [comment]
你好，谢谢你的帮助，可以的话请提供一个这样的天凤账号名称，方便我做测试。我所知道的大多数这样的机器人是uuz、Freeze_Kirin、hoshino插件，前两者功能更强大，相对于我的设计更早，能够实现websocket直接观战牌局，这些是我目前办不到的

**Comment by Sunshine40** [comment]
Freeze_Kirin是他人设计的？原来如此。不过我觉得能有一个开源的项目可以自己改进也很不错。目前的阶段确实待改进的空间很大（笑）

关于bug复现，示例账号是tenhou君。

这个bug我已经修了，看下pull request
